config/routes.rb
Dining::Application.routes.draw do
  root "restaurants#index"

  resources :restaurants do
    collection do
      get :search
    end
  end
end

app/models/concerns/searchable.rb
require 'elasticsearch/model'

module Searchable
  extend ActiveSupport::Concern

  def self.index_name
    Rails.application.class.parent_name.underscore
  end

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    index_name Searchable.index_name

    def self.search_by(type, query)
      return self.all if query.blank?
      self.search query: {match: {type => query}}
    end
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  include Searchable

  mappings dynamic: 'false' do
    indexes :name, type: 'string', analyzer: 'mmseg_complex'
    indexes :price, type: 'integer'
  end

  def self.search_by_name(name)
    return [] if name.blank?
    self.search(
         min_score: 1,
         query: {match: {name: name}},
         sort: [
                  {price: {order: :asc}},
                  {_score: {order: :desc}},
                ],
         size: 30,
         )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant
      .order('price desc')
      .paginate(page: params[:page], per_page: 20)
  end

  def search
    @restaurants = Restaurant.search_by_name(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.haml
#footer
  .container
    .left.nav.navbar-nav
      = link_to "站长", "http://blog.linjunhalida.com/about"
      %span= "|"
      = link_to "关于", '#', id: 'about'

    .right.nav.navbar-nav.navbar-right

app/views/layouts/_nav.haml
.navbar.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: '/'} 上海好食汇
  
    .collapse.navbar-collapse
      %ul.nav.navbar-nav

      %ul.nav.navbar-nav.navbar-right

app/views/layouts/_notify.haml
.notifications
  .inner
= run :msg, text: flash[:notice] if flash[:notice].present?

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: 'utf-8'}
    %title= @title || 'dining'
    %meta{name: 'description', content: @desc || ''}
    %meta{name: 'author', content: ''}
    %meta{name: 'keywords', content: 'dining,shanghai'}
    %link{rel: "shortcut icon", href: image_path("icon.png")}

    :plain
        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    = stylesheet_link_tag "application.css"
    = csrf_meta_tag

  %body.website{class: "#{'embed' if session[:embed]}"}
    
    = render partial: "layouts/nav" unless session[:embed]
    = render partial: "layouts/notify"

    .container
      = yield

    = render partial: "layouts/footer"

    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application.js", debug: false

app/views/pages/index.html.haml
hello

app/views/restaurants/_list.haml
.restaurant.list
  = will_paginate restaurants if action_name == 'index'

  - if restaurants.empty?
    .empty
      没有任何结果
  - else
    %table.table.table-striped.table-hover.table-bordered
      %thead
        %tr
          %th 名字
          %th 地点
          %th 描述
          %th 价位
    
      %tbody
        - restaurants.each do |r|
          %tr
            %td= r.name
            %td= r.location
            %td= r.description
            %td= '$' * r.price
  
  = will_paginate restaurants if action_name == 'index'

app/views/restaurants/index.html.haml
%h1 餐馆列表

.search
  = form_tag search_restaurants_path, method: :get do
    = label_tag "搜索您想要的餐馆"
    = text_field_tag :q, params[:q]
    = submit_tag "搜索", class: "btn btn-primary"

= render partial: "list", locals: {restaurants: @restaurants}

app/views/restaurants/search.html.haml
.search
  = form_tag search_restaurants_path, method: :get do
    = label_tag "搜索您想要的餐馆"
    = text_field_tag :q, params[:q]
    = submit_tag "搜索", class: "btn btn-primary"

    或者
    = link_to "查看所有", restaurants_path

= render partial: "list", locals: {restaurants: @restaurants}